spring:
  first-datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/first
    username: sa
    password:
  second-datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/second
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
